# Generated by Django 4.1.7 on 2023-03-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir', models.CharField(max_length=200, verbose_name='目录')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='哈希')),
            ],
        ),
    ]
