# Generated by Django 4.1.7 on 2023-03-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': '资源', 'verbose_name_plural': '资源'},
        ),
        migrations.AddField(
            model_name='resource',
            name='hash',
            field=models.CharField(default=None, max_length=200, unique=True, verbose_name='哈希'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='名称'),
        ),
    ]
