# Generated by Django 4.1.7 on 2023-03-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_resource_options_resource_hash_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
        migrations.RemoveField(
            model_name='resource',
            name='hash',
        ),
        migrations.AddField(
            model_name='resource',
            name='file',
            field=models.FileField(default=None, upload_to='uploads/%Y/%m/', verbose_name='File'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='dir',
            field=models.CharField(max_length=200, verbose_name='Dir'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
    ]
