# Generated by Django 4.1.7 on 2023-03-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_resource_options_remove_resource_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='dir',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='name',
        ),
    ]
